# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_id_google_sheet_ici"
GSPREAD_WORKSHEET_NAME = "NomOnglet"

# Si besoin de configurer d'autres secrets :
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/..."