# .streamlit/secrets.toml

OPENAI_API_KEY = "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"
GSPREAD_SHEET_ID = "votre_id_google_sheet_ici"
GSPREAD_WORKSHEET_NAME = "NomOnglet"

# Si besoin de configurer d'autres secrets :
# DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/..."